from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Literal

StepStatus = Literal[
    "PENDING",
    "RUNNING",
    "PASS",
    "FAIL",
    "BLOCKED",
]

EventLevel = Literal[
    "DEBUG",
    "INFO",
    "WARNING",
    "ERROR",
]


def utc_now() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class ProjectState:
    """Canonical project state consumed by the monitoring system."""

    project: str = "Einstein AI V2"
    version: str = "0.1.0"

    current_phase: str = "0.6.2"
    current_step: str = "Monitoring Project State + Event Schema"

    status: StepStatus = "RUNNING"

    progress_percent: float = 0.0

    active_branch: str = ""
    current_commit: str = ""

    started_at: str = field(default_factory=utc_now)
    updated_at: str = field(default_factory=utc_now)

    completed_steps: list[str] = field(default_factory=list)
    active_steps: list[str] = field(default_factory=list)

    tests_passed: int = 0
    tests_failed: int = 0

    warnings: int = 0
    errors: int = 0

    last_event_id: str | None = None

    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the project state into a JSON-compatible dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProjectState:
        """Restore project state from a dictionary."""
        return cls(**data)


@dataclass
class ProjectEvent:
    """Immutable audit event generated by the monitoring system."""

    event_id: str
    timestamp: str

    phase: str
    step: str

    event_type: str
    level: EventLevel

    message: str

    status: StepStatus | None = None

    branch: str | None = None
    commit: str | None = None

    progress_percent: float | None = None

    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the event into a JSON-compatible dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProjectEvent:
        """Restore an event from a dictionary."""
        return cls(**data)


def validate_project_state(state: ProjectState) -> list[str]:
    """Validate canonical project-state values."""

    errors: list[str] = []

    if not state.project:
        errors.append("project is required")

    if not state.current_phase:
        errors.append("current_phase is required")

    if not state.current_step:
        errors.append("current_step is required")

    if not 0.0 <= state.progress_percent <= 100.0:
        errors.append("progress_percent must be between 0 and 100")

    if state.tests_passed < 0:
        errors.append("tests_passed cannot be negative")

    if state.tests_failed < 0:
        errors.append("tests_failed cannot be negative")

    if state.warnings < 0:
        errors.append("warnings cannot be negative")

    if state.errors < 0:
        errors.append("errors cannot be negative")

    return errors


def validate_project_event(event: ProjectEvent) -> list[str]:
    """Validate an immutable monitoring event."""

    errors: list[str] = []

    if not event.event_id:
        errors.append("event_id is required")

    if not event.timestamp:
        errors.append("timestamp is required")

    if not event.phase:
        errors.append("phase is required")

    if not event.step:
        errors.append("step is required")

    if not event.event_type:
        errors.append("event_type is required")

    if not event.message:
        errors.append("message is required")

    if event.progress_percent is not None and not 0.0 <= event.progress_percent <= 100.0:
        errors.append("progress_percent must be between 0 and 100")

    return errors


def state_to_json(state: ProjectState) -> str:
    """Serialize project state as formatted JSON."""

    errors = validate_project_state(state)

    if errors:
        raise ValueError("Invalid project state: " + "; ".join(errors))

    return json_dumps(state.to_dict())


def event_to_json(event: ProjectEvent) -> str:
    """Serialize an event as formatted JSON."""

    errors = validate_project_event(event)

    if errors:
        raise ValueError("Invalid project event: " + "; ".join(errors))

    return json_dumps(event.to_dict())


def json_dumps(data: dict[str, Any]) -> str:
    """Stable JSON serialization helper."""

    import json

    return json.dumps(
        data,
        ensure_ascii=False,
        sort_keys=True,
    )
